"       _
"__   _(_)_ __ ___  _ __ ___
"\ \ / / | '_ ` _ \| '__/ __|
" \ V /| | | | | | | | | (__
"(_)_/ |_|_| |_| |_|_|  \___|

" vimrc with little tweaks
" Author: Shreyas
 
" show numbers as default
:set number

" some plugin manager stuff
execute pathogen#infect()
syntax on
filetype plugin indent on

" plugin imports
call plug#begin()

Plug 'ryanoasis/vim-devicons'
Plug 'tiagofumo/vim-nerdtree-syntax-highlight'
Plug 'https://github.com/ap/vim-css-color.git' 
Plug 'PotatoesMaster/i3-vim-syntax'

call plug#end()

" youcompleteme
let g:ycm_global_ycm_extra_conf = "/home/shreyas/.vim/bundle/YouCompleteMe/.ycm_extra_conf.py"

" Dracula color scheme
packadd! dracula
syntax enable
colorscheme dracula

"  Status Line
" The lightline.vim theme
let g:lightline = {
      \ 'colorscheme': 'darcula',
      \ }

set laststatus=2
set noshowmode

" tabwidth change for java
autocmd Filetype java setlocal tabstop=2
autocmd Filetype java setlocal shiftwidth=2
set encoding=utf-8
 
" Split settings

set splitbelow splitright

" Remapping move keys to only ctrl+<vim keys>
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

